### ISSUE TITLE
GA returns most recent (rather than best) value?

### ISSUE THREAD

**Issue by timholy** [wildart/Evolutionary.jl#106]
I'm using GA to perform a combinatorial optimization, with the goal of finding a pair of permutations that minimize an objective. I'm finding that the minimum/minimizer from `Evolutionary.optimize` appears to be the last value tried rather than the lowest value tried.

The easiest way to report this is to point to an in-progress repository: https://github.com/timholy/ScheduleMeetings.jl. Currently it's set up to show a trace; when I run the tests (which are equivalent to the demo in the README), the tail end looks like this:

```
   993               31
 * time: 0.13976812362670898
   994               46
 * time: 0.13983798027038574
   995           100046
 * time: 0.1405642032623291
   996               22
 * time: 0.14065003395080566
   997           100028
 * time: 0.14070606231689453
   998               66
 * time: 0.1408231258392334
   999               66
 * time: 0.14092206954956055
  1000               59
 * time: 0.14101600646972656
Evolutionary.minimum(result) = 59
f(perm0) = 14
Evolutionary.minimizer(result) = [2, 1, 3, 3, 2, 1]
perm0 = [1, 2, 3, 1, 2, 3]
```

`perm0` is the initial permutation pair (effectively `vcat(perm1, perm2)`), and `f(perm0)` is the objective value. You can see here that the input is better than the returned value.

**Comment by daviehh** [comment]
Also ran into this issue with the `DE()` algorithm at #112 , guess with the `GA` the results from previous iteration (which contain the actual minimizer) can be overwritten by later iterations, possibly somewhere

https://github.com/wildart/Evolutionary.jl/blob/cf3f2fbf5e1be13d6f5db23eabe5dbfab4d5b688/src/ga.jl#L92-L97

for the GA.

**Comment by daviehh** [comment]
Would the test result at commit https://github.com/timholy/ScheduleMeetings.jl/commit/1dae62f2daa6f6767166586a7401d57fd4bfc922

```
Iter     Function value
     0               14
 * time: 0.00019502639770507812
     1               14
 * time: 0.018580913543701172
     2               14
 * time: 0.018917083740234375
     3               14
 * time: 0.01920604705810547
     4               14
 * time: 0.01949787139892578
     5               14
 * time: 0.019734859466552734
     6               14
 * time: 0.019989013671875
     7               14
 * time: 0.02025890350341797
     8               14
 * time: 0.020509958267211914
     9               14
 * time: 0.02074599266052246
    10               14
 * time: 0.020987987518310547
    11               14
 * time: 0.0212399959564209
    12               14
 * time: 0.021517038345336914
Evolutionary.minimum(result) = 14
f(perm0) = 14
Evolutionary.minimizer(result) = [1, 2, 3, 1, 2, 3]
perm0 = [1, 2, 3, 1, 2, 3]
```
in agreement with what you expect? Got the result above when changing the minimize logic here
https://github.com/wildart/Evolutionary.jl/blob/cf3f2fbf5e1be13d6f5db23eabe5dbfab4d5b688/src/ga.jl#L93-L94

with
```julia
if (minfit < state.fitness)
     state.fittest = offspring[fitidx]
     state.fitness = state.fitpop[fitidx]
end
```
to avoid the result being overwritten by later iterations when it's not actually the optimized minimizer

**Comment by timholy** [comment]
In the `main` branch I've modified the test to be a little more challenging (that solution is optimal, but it's also the initial guess). You could try your code patch with the current test?

**Comment by wildart** [comment]
You may want to play with a mutation rate (decrease) or population size (increase) for more stable performance. Plus, instead of the default `tournament` selector, you could use more aggressive `susinv` to drive a population of low fitness permutations up.

I also found that the best permutation is `[2, 2, 3, 1, 1, 3]` with the fitness value `21`, and it isn't possible to get such permutation with your mutation function  `swap2blocks` as it only swaps numbers within a block. So, the starting permutation `[1, 2, 3, 1, 2, 3]` appears to be an optimal choice.

**Comment by timholy** [comment]
In #108 I raised the question of whether it would make sense to provide an option to preserve the best-so-far individual ("elite" individuals are still subject to mutation, and hence they can be degraded as well as improved). Perhaps a copy could be made before mutation, so that you'd be sure to avoid any worsening? I'd defer to @wildart who knows much more than I about such matters.

**Comment by wildart** [comment]
Indeed, the current implementation mutates elite population, and this is unconventional to the common practice of elitism implementation. It's worth considering to copy elite individuals intact.
