### ISSUE TITLE
DE returns most recent population info, rather than the minimizer

### ISSUE THREAD

**Issue by daviehh** [wildart/Evolutionary.jl#112]
May be related to #106, while my function is a bit too complicated to set up a minimum example, I find that the result returned by the `DE()` algorithm would give the minimizer from the last iteration, rather than the one giving the minimum values.

Going through the code, it looks like 
https://github.com/wildart/Evolutionary.jl/blob/cf3f2fbf5e1be13d6f5db23eabe5dbfab4d5b688/src/de.jl#L78

sets the minfit to Inf at each iteration, and find the minimum w/ population index. As a result, the population index from an earlier iteration corresponding to the actual minimizer may be overwritten at a later iteration at
https://github.com/wildart/Evolutionary.jl/blob/cf3f2fbf5e1be13d6f5db23eabe5dbfab4d5b688/src/de.jl#L85-L87

Changing the line
https://github.com/wildart/Evolutionary.jl/blob/cf3f2fbf5e1be13d6f5db23eabe5dbfab4d5b688/src/de.jl#L78

to 

`minfit = minimum(state.fitness)`

fixes the problem.

**Comment by wildart** [comment]
Thanks, nice catch.
