### ISSUE TITLE
ES selection strategies

### ISSUE THREAD

**Issue by DrChainsaw** [wildart/Evolutionary.jl#116]
Intuitively it seems to me that the "traditional" GA selection functions (e.g. roulette, tournament and sus) are in principle just as applicable to ES, but from my understanding the selection for `Evolutionary.ES` is limited to `:plus` and `:comma` which from what I understand from the code just selects individuals randomly without any regard to fitness. 

Is there something preventing having this as an option (e.g. they are not useful for ES)?

**Comment by wildart** [comment]
ES selection rules are quite specific. Both ES selection mechanisms, `+/,` use a subset of individuals, with minimal fitness. It's not random. For more explicit control over the selection mechanism, you'd better use GA where the section is performed by a custom function.

If you want to compare ES selection to GA, it would be following:
- ES `comma`-selection is GA truncation selection
- ES `plus`-selection is GA truncation selection with elitism (kind of).

**Comment by DrChainsaw** [comment]
Ok, are they interchangeable like that? The docs gave me the impression that the GA only works on a population of bitarrays.

**Comment by DrChainsaw** [comment]
They indeed are! No idea how I could misunderstand the docs like that 😊
