### ISSUE TITLE
Errors with Julia 0.5.0

### ISSUE THREAD

**Issue by rsturley** [wildart/Evolutionary.jl#13]
There are some errors using this with Julia 0.5.0. If you change the following lines in Evolutionary.jl
and ga.jl, it seems to work fine.

Evolutionary.jl:22:    typealias Individual Union{Vector, Matrix, Function, Void}
ga.jl:17:            lowerBounds::Union{Void, Vector} = nothing,
ga.jl:18:            upperBounds::Union{Void, Vector} = nothing,

**Comment by wildart** [comment]
Checkout current master for julia 0.5 & 0.6 compatible code.
