### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by Ayush-iitkgp** [wildart/Evolutionary.jl#14]
Hello,
We are trying to provide the Evolutionary.jl as the backend optimizer for the cost function in [DiffEqParameEstim.jl](https://github.com/JuliaDiffEq/DiffEqParamEstim.jl) See https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/issues/25. The present release is not compatible with Julia 0.5 and 0.6. Do you plan to release a new version which provides support for recent julia versions? 
I am happy to help :)

**Comment by wildart** [comment]
Checkout current master for julia 0.5 & 0.6 compatible code.
