### ISSUE TITLE
ga() parameters `lowerBounds` and `upperBounds` do nothing

### ISSUE THREAD

**Issue by 0x47** [wildart/Evolutionary.jl#15]
It seems that the parameters `lowerBounds` and `upperBounds` in the genetic algorithm have no function. Without those bounds, the search space for integer variables is too big and the algorithm fails to find a solution. Any chance those parameters can be implemented?

**Comment by rrsk** [comment]
Can I work on this issue ?

**Comment by phelipe** [comment]
Any news?

**Comment by wildart** [comment]
@rrsk Give it a try.

**Comment by wildart** [comment]
Fixed in v0.7.0
