### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by ChrisRackauckas** [wildart/Evolutionary.jl#16]

**Comment by ChrisRackauckas** [comment]
Bump

**Comment by jlopezbi** [comment]
For anyone who wants to use this package with the newer version of Julia, run 
`Pkg.checkout("Evolutionary")` to get the updated version of the package. This should remove the deprecated syntax error. (I am using version 0.6.1 of Julia)

**Comment by ChrisRackauckas** [comment]
Yes but that doesn't help CI tests though.

**Comment by wildart** [comment]
Use latest version compatible with julia 1.0. See README.md for installation instructions.
