### ISSUE TITLE
Test showing error on master package

### ISSUE THREAD

**Issue by rrsk** [wildart/Evolutionary.jl#20]
I see the following error, might be due to some dependencies 

On running   -> Pkg.test("Evolutionary")

INFO: Testing Evolutionary
Running tests:
	FAILED: sphere.jl
LoadError: LoadError: MethodError: no method matching Union(::Type{Array{T,1}}, ::Type{Array{T,2}}, ::Type{Function}, ::Type{Void})
Closest candidates are:
  Union{T}(::Any) at sysimg.jl:53
 in macro expansion; at /home/rishab/.julia/v0.5/Evolutionary/test/runtests.jl:25 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/rishab/.julia/v0.5/Evolutionary/src/Evolutionary.jl, in expression starting on line 22
while loading /home/rishab/.julia/v0.5/Evolutionary/test/sphere.jl, in expression starting on line 2
	FAILED: rosenbrock.jl
LoadError: UndefVarError: es not defined
 in macro expansion; at /home/rishab/.julia/v0.5/Evolutionary/test/runtests.jl:25 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/rishab/.julia/v0.5/Evolutionary/test/rosenbrock.jl, in expression starting on line 20
	FAILED: schwefel.jl
LoadError: UndefVarError: cmaes not defined
 in macro expansion; at /home/rishab/.julia/v0.5/Evolutionary/test/runtests.jl:25 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/rishab/.julia/v0.5/Evolutionary/test/schwefel.jl, in expression starting on line 19
	FAILED: rastrigin.jl
LoadError: UndefVarError: es not defined
 in macro expansion; at /home/rishab/.julia/v0.5/Evolutionary/test/runtests.jl:25 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/rishab/.julia/v0.5/Evolutionary/test/rastrigin.jl, in expression starting on line 27
	FAILED: n-queens.jl
LoadError: UndefVarError: inversion not defined
 in macro expansion; at /home/rishab/.julia/v0.5/Evolutionary/test/runtests.jl:25 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/rishab/.julia/v0.5/Evolutionary/test/n-queens.jl, in expression starting on line 28
INFO: Evolutionary tests passed

"The test seems to be passed yet the source of errors is unknown to me"

**Comment by phelipe** [comment]
Try using: 
Pkg.checkout("Evolutionary").

**Comment by wildart** [comment]
Use latest version compatible with julia 1.0. See README.md for installation instructions.
