### ISSUE TITLE
Error while utilizing Julia 0.6.2 on Windows 10

### ISSUE THREAD

**Issue by Dkmister** [wildart/Evolutionary.jl#22]
My code has the following first line:
_Using Evolutionary_

Then it appears that error:

WARNING: deprecated syntax "typealias Strategy Dict{Symbol,Any}" at C:\Users\Vilmar\.julia\v0.6\Evolutionary\src\Evolutionary.jl:22.
Use "const Strategy = Dict{Symbol,Any}" instead.

WARNING: deprecated syntax "typealias Individual Union(Vector,Matrix,Function,Nothing)" at C:\Users\Vilmar\.julia\v0.6\Evolutionary\src\Evolutionary.jl:23.
Use "const Individual = Union(Vector,Matrix,Function,Nothing)" instead.
ERROR: LoadError: LoadError: MethodError: no method matching Union(::Type{Array{T,1} where T}, ::Type{Array{T,2} where T}, ::Type{Function}, ::Type{Void})
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
while loading C:\Users\Vilmar\.julia\v0.6\Evolutionary\src\Evolutionary.jl, in expression starting on line 22
while loading C:\Users\Vilmar\Documents\Otimizacao Comb\Programas\knapsack_ga.jl, in expression starting on line 1

What should I do?

**Comment by phelipe** [comment]
Did you try Pkg.checkout("Evolutionary")?

**Comment by Dkmister** [comment]
I know now how to fix this. You have to ```Pkg.clone("git://github.com/wildart/Evolutionary.jl")``` instead of using the ```Pkg.add()``` .

But first I've had to ```` Pkg.remove("Evolutionary") ```

That's it. It solved in my Ubuntu on WSL. It should work on Windows too.

**Comment by wildart** [comment]
Use latest version compatible with julia 1.0. See README.md for installation instructions.
