### ISSUE TITLE
1.0 compatibility

### ISSUE THREAD

**Issue by d9w** [wildart/Evolutionary.jl#23]
Hi :) very nice library, thanks. I'm wondering if you're planning on updating this to work with 1.0 any time soon? Currently it doesn't compile (Void is no longer a type is the first error I'm getting, but there might be more)

**Comment by andrewkeenan** [comment]
I'm in the process of updating this. Will PR when ready.

**Comment by wildart** [comment]
Fixed in #25. See [README.md](https://github.com/wildart/Evolutionary.jl/blob/master/README.md) for installation instructions.
