### ISSUE TITLE
Re-use code for BlackBoxOptim.jl?

### ISSUE THREAD

**Issue by robertfeldt** [wildart/Evolutionary.jl#28]
Thanks for this package, it looks great.

We have the implementation of CMA-ES and ES etc on the todo list for the BlackBoxOptim.jl (BBO) package but since this seems to be a nice implementation I wonder if you would be ok with us basing our implementation of them on your code? 

My interpretation is that your license does allow it but I want to make sure anyway. I see value in both having this smaller and more direct implementation and including it in a framework/lib like BBO where one can easily switch between different optimization algorithms.

**Comment by wildart** [comment]
I've no problem with that.
