### ISSUE TITLE
Issue while loading in Julia 0.5.2

### ISSUE THREAD

**Issue by apeano** [wildart/Evolutionary.jl#31]
Hello,
in Julia 0.5.2 the using instruction gives this error:
`
julia> using Evolutionary
ERROR: LoadError: MethodError: no method matching Union(::Type{Array{T,1}}, ::Type{Array{T,2}}, ::Type{Function}, ::Type{Void})
Closest candidates are:
  Union{T}(::Any) at sysimg.jl:53
 in include_from_node1(::String) at .\loading.jl:488
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:415
while loading C:\Users\a.peano\.julia\v0.5\Evolutionary\src\Evolutionary.jl, in expression starting on line 22
`

Do you have any idea on how to bypass it?

Thanks

**Comment by phelipe** [comment]
Do you need to use language version 0.5? Julia is currently in version 1.1.

**Comment by apeano** [comment]
Thanks for your reply.
Yes, unless I rewrite my libraries, but I cannot effor it now.

Do you think I can modify some lines to make it working on 0.5.2? Or it needs a huge refactoring.

Thanks

**Comment by phelipe** [comment]
I believe that errors are associated with declaring different types and functions between version 0.6 and 0.5, so you would have to modify them in code. One possibility would be to take a look at:

https://github.com/JuliaComputing/FemtoCleaner.jl

**Comment by wildart** [comment]
@apeano Checkout `v0.2.0` this is a last version that supports julia v0.5 & v0.6

**Comment by apeano** [comment]
It seems the v0.2.0 is the last one... Do you mean a previous one?

**Comment by apeano** [comment]
By the way, the documentation says
"For julia 0.6 and lower, run following command".
I followed this suggestion

**Comment by wildart** [comment]
@apeano Try `Pkg.checkout("Evolutionary", v"0.2.0")`
