### ISSUE TITLE
In-place mutation

### ISSUE THREAD

**Issue by aahaselgrove** [wildart/Evolutionary.jl#33]
I'm trying to find a Genetic Algorithms implementation for a project I'm working on, so have been looking through the code. Is mutation applied in-place, or do I misunderstand? On one hand, the code is clearly discarding the return value from mutation:
https://github.com/wildart/Evolutionary.jl/blob/c7fb224c7d17691aaff0f5ce63987df9f3329c97/src/ga.jl#L87-L94

But on the other hand, the sample mutations in mutations.jl (and the default mutation (x -> x)) all return a value and aren't suffixed with a `!`.

**Comment by wildart** [comment]
True, all mutations in this package are in-place. There wasn't any need in a mutated copy, even though all functions return values. As for the naming convention, I wasn't paying match attention to it when I wrote some. Package definitely requires some refactoring and documentation update.

**Comment by wildart** [comment]
Added a note to the docs, https://wildart.github.io/Evolutionary.jl/dev/mutation/
