### ISSUE TITLE
Support for multidimensional individuals

### ISSUE THREAD

**Issue by aahaselgrove** [wildart/Evolutionary.jl#35]
I'm currently looking at a problem I'm trying to apply GA to which has 2D individuals. This implementation only supports 1D individuals but I don't see any reason not to support individuals of arbitrary dimension.

Major changes required are to getIndividual and population generation. The easy way to do this would probably be to change the dimensionality parameter N to instead specify the type of an individual.

What are your thoughts?

**Comment by phelipe** [comment]
What are 2D individuals?

**Comment by aahaselgrove** [comment]
I considered this, but looking at the code, the restriction forcing inputs to be 1D vectors seems to be arbitrary and the only impact is on interpreting the initPopulation parameter - hence, my suggestion to widen support. I'm currently investigating this on a local fork.

**Comment by phelipe** [comment]
For me it makes no sense to use 2D arrays, you will have to modify the whole package, besides GA and DE consider vectors in their theoretical definition.  As with convex optimization problems, you need to rewrite your problem before the solver can solve it.

**Comment by wildart** [comment]
Majority of mutation and recombination operations work on vectors only. You'll need to write your own for 2D transfomations.

**Comment by wildart** [comment]
Implemented in new api, see [Docs/Dev/Population](https://wildart.github.io/Evolutionary.jl/dev/dev/#Population-1)
