### ISSUE TITLE
Support for binary chromosomes?

### ISSUE THREAD

**Issue by DataWookie** [wildart/Evolutionary.jl#4]
Hi,

I have been exploring Julia's GA capabilities, looking at GeneticAlgorithms and Evolutionary packages. I really enjoy the simple interface presented by Evolutionary and it also seems to be more advanced in terms of development. Great work and thank you for your efforts.

However, I am having trouble figuring out how I can implement a binary GA. I am using a knapsack problem as a simple illustrative example. I've written a fitness function which looks like this:

    mass    = [1, 5, 3, 7, 2, 10, 5]
    utility = [1, 3, 5, 2, 5,  8, 3]
    
    function fitness(n::Vector{Int})
        total_mass = sum(mass .* n)
        return (total_mass <= 20) ? sum(utility .* n) : 0
    end

but when I try to run the GA as follows

    ga(fitness, 7)

I get

    ERROR: wrong number of arguments
     in anonymous at /home/colliera/.julia/v0.3/Evolutionary/src/ga.jl:23
     in ga at /home/colliera/.julia/v0.3/Evolutionary/src/ga.jl:66

Looking at the debug output from `ga()` I see that the vectors being passed into my fitness function are floating point rather than binary (or at least a vector of integer 0 or 1). I'm not sure whether this is the source of the ERROR above, but it's certainly something that I need to resolve in order to get my problem up and running.

Is there support for binary chromosomes? Have I missed something?

Best regards,
Andrew.

**Comment by wildart** [comment]
It is just default `selection` and `crossover` functions are incorrect. Try some other functions.

**Comment by wildart** [comment]
If you call you example as follows:
```julia
julia> ga(fitness, 7, selection=((x,n)->1:n))
([0.878847,0.226192,0.713515,0.874419,0.659458,0.534775,0.706383],0,700,0)
```
If you want binary chromosomes use `Vector{Bool}` to initialize population (for some reason `BitVector` isn't supported}:
```julia
julia> ga(fitness, 7, selection=((x,n)->1:n), initPopulation = collect(randbool(7)))
(Bool[false,true,false,true,true,false,false],10,700,0)
```

**Comment by DataWookie** [comment]
Thank you, that sorted out the problem perfectly!
