### ISSUE TITLE
The best elite could be overwritten. 

### ISSUE THREAD

**Issue by stephenll** [wildart/Evolutionary.jl#44]
I would think that when setting up the GA with a setting utilizing `elite` the best fit in each population  should be guaranteed to survive.  It seems it is possible to overwrite for example the best fit with one that isn't.

I would expect that if we are selection a certain percentage or number of elite to move to the next population that the `best` n of them would be available.

I have seen in multiple runs where I have an initial population that contains  the best known to date, I will see the `best` in a population be actually worse than the `best` I set in the initial population.

I can trace the problem in ga.jl to the code below.  The `subs = rand(1:populationSize` and `offspring[subs] = population[fitidx[i]]`can easily overwrite the most elite with one that isn't the `best`. 

I had a run where the best of a population was in location 10, then was assigned to position 19 in `offspring`, then another elite that wasn't as good as the best, was assigned over that location of 19.  Now the best in the population doesn't move forward.

```
if elite > 0
            for i in 1:elite
                subs = rand(1:populationSize)
                debug && println("ELITE $(fitidx[i])=>$(subs): $(population[fitidx[i]]) => $(offspring[subs])")
                offspring[subs] = population[fitidx[i]]
            end
        end
```

**Comment by wildart** [comment]
>  The subs = rand(1:populationSize) and offspring[subs] = population[fitidx[i]] can easily overwrite the most elite with one that isn't the best.

You are right. That random index can point to a previously copied elite individual. Moreover,  it overwrites some of the newly generated offspring which is the waist.

**Comment by stephenll** [comment]
When I wrote my own GA in the past for a company I was working for, I made sure the new generation was nElite = ceil(elitepct*nPopulation), nCrossOver = round(crossPct*(nPopulation - nElite)), nMutate = nPopulation - nElite - nCrossOver.  I am just learning Julia or I would try to help more.

**Comment by wildart** [comment]
> nMutate = nPopulation - nElite - nCrossOver

So, you never applied mutation to the crossover offspring. Why?

**Comment by stephenll** [comment]
Caveat: I don't have formal training in Genetic Algorithms.  I feel that applying a mutation to a crossover is applying changes twice and goes against what a GA is fundamentally laying out.  Some of the population is going to be from the elite group, another portion is going to be from the crossover of select parents, and some are going to be from the mutation of the parents.  Mutating a crossover seemed overkill.  Restricting the number of elite moving forward and a form of scaling for the parent selection can make for a better diverse population.

**Comment by wildart** [comment]
I couldn't find clear answer as well, but giving small joint probability of simultaneous crossover and mutation operations, applying both to the offspring should not be a problem.

**Comment by stephenll** [comment]
I dug around a little.

Per David Goldberg’s book: Genetic Algorithms in Search, Optimization and Machine Learning, the mutation is supposed to protect from the crossover function losing important information or being "overzealous.”

Based on that, I would say that the mutation should be based off the parent and not a crossover.

I am going to continue reading the book and see what else I can learn.
