### ISSUE TITLE
Have an `optimize`  function to use different algorithms with the same function?

### ISSUE THREAD

**Issue by abhigupta768** [wildart/Evolutionary.jl#46]
Hey, we wanted to add Evolutionary.jl as one of the optimization backends in DiffEqFlux.jl https://github.com/SciML/DiffEqFlux.jl/issues/186, but not having a single function to call for different algorithms makes it a little awkward to handle. If you think this would be a good idea I could start working on a PR for this?

**Comment by wildart** [comment]
Why do you need a one function for calling quite different algorithms? Can you elaborate more on it?

**Comment by abhigupta768** [comment]
I think it makes it easier to provide user the ability to use the package and experiment with different algorithms, the arguments could be different for different algorithms undoubtedly but it is just much more convenient to use a single function and swap out args for the method you want to use.

You can take a look at how we are doing it for other packages like Optim, BlackBoxOptim and NLopt.
https://github.com/SciML/DiffEqFlux.jl/blob/master/src/train.jl#L268

https://github.com/SciML/DiffEqFlux.jl/blob/master/src/train.jl#L328 

https://github.com/SciML/DiffEqFlux.jl/blob/master/src/require.jl#L34

**Comment by wildart** [comment]
It would be nice to define types for algorithms which will hold the particular parameters, and use objects of these types to pass to the `optimize` function e.g.

```julia
result = optimize(GA(populationSize = 100, ɛ = 0.1, selection = sus), objfunc)
```
Moreover, a common result type, at least an abstract type, is needed as well.

**Comment by abhigupta768** [comment]
Can we do a new release now?

**Comment by wildart** [comment]
It's coming. Meanwhile, I began to work on next version of `optimize` interface, see #49. So the API will change a bit later.
