### ISSUE TITLE
How to set `bounds` properly?

### ISSUE THREAD

**Issue by GiggleLiu** [wildart/Evolutionary.jl#59]
One can specify the `ConstraintBounds` as the optimizer input, however, it is more likely designed for lagrange multiplier.

It does take effect during population generation of `CMAES`:

https://github.com/wildart/Evolutionary.jl/blob/af63c9523fc0f401ed4aabfe8cf9f6c2b6055aff/src/cmaes.jl#L147

Currently, I need a bound that populations can be cliped on this bounds like
```julia
clip!(generated_population, bounds)
```
Do you think it is proper to add a new `bounds` as field of `CMAES`? Naively, the bounds type should contain a vector of upper bounds and a vector of lower bounds. Any comments?

**Comment by GiggleLiu** [comment]
I will try to submit a PR.

**Comment by wildart** [comment]
Implemented in v0.7.0
