### ISSUE TITLE
MixedInt example fails - UndefVarError: WorstFitnessConstraints not defined

### ISSUE THREAD

**Issue by evrenmturan** [wildart/Evolutionary.jl#63]
I can't get the mixed interger example code to run as is. I get UndefVarError for MixedTypePenaltyConstraints,WorstFitnessConstraints and MILX.

**Comment by wildart** [comment]
Do you use most  recent `master` code?

**Comment by evrenmturan** [comment]
I think so. No update on using pkg, and pkg> status shows that  Evolutionary version v0.7.0.

**Comment by evrenmturan** [comment]
Apologies, I added the package directly with pkg> add github.com/wildart/Evolutionary.jl , and everything works now. Sorry I am new to julia...
