### ISSUE TITLE
Error: objects of type Float64 are not callable

### ISSUE THREAD

**Issue by BuRanran** [wildart/Evolutionary.jl#68]
Thanks for your work. And there is an error in my code, could you please point out the mistakes?

`fitFunc(w)=w[1]-w[2]+w[3]-w[4]+w[5]-w[6]

lx = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
ux = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
con_w = w[1]+w[2]+w[3]+w[4]+w[5]+w[6]
lc = [1.0]
uc = [1.0]

mthd = GA(populationSize = 3, ɛ = 0.03, selection = susinv, crossover = intermediate(0.7), mutation = gaussian(2))
con = PenaltyConstraints(1e3, lx, ux, lc, uc, con_w)
Evolutionary.ConstraintBounds(lx,ux,lc,uc), con_w)
opts = Evolutionary.Options(iterations=15, successive_f_tol=25,  show_trace=true)

res_Final = Evolutionary.optimize(fitFunc, con, con.bounds, mthd, opts)
m = Evolutionary.minimizer(res_Final)
minimum(res_Final)`

There is a error at the line of function “optimize”, that "Error: objects of type Float64 are not callable".
In detail:
LoadError: MethodError: objects of type Float64 are not callable
in expression starting at D:\\gaspipeline_sto.jl:212
value(::PenaltyConstraints{Float64,Float64}, ::NonDifferentiable{Float64,Array{Float64,1}}, ::Array{Float64,1}) at constraints.jl:138
update_state!(::NonDifferentiable{Float64,Array{Float64,1}}, ::PenaltyConstraints{Float64,Float64}, ::Evolutionary.GAState{Float64,Array{Float64,1}}, ::Array{Array{Float64,1},1}, ::GA, ::Int64) at ga.jl:98
optimize(::NonDifferentiable{Float64,Array{Float64,1}}, ::PenaltyConstraints{Float64,Float64}, ::Array{Array{Float64,1},1}, ::GA, ::Evolutionary.Options{Nothing}, ::Evolutionary.GAState{Float64,Array{Float64,1}}) at optimize.jl:56
optimize(::NonDifferentiable{Float64,Array{Float64,1}}, ::PenaltyConstraints{Float64,Float64}, ::Array{Array{Float64,1},1}, ::GA, ::Evolutionary.Options{Nothing}) at optimize.jl:40
optimize(::Function, ::PenaltyConstraints{Float64,Float64}, ::NLSolversBase.ConstraintBounds{Float64}, ::GA, ::Evolutionary.Options{Nothing}) at optimize.jl:31
top-level scope at gaspipeline_sto.jl:212
include_string(::Function, ::Module, ::String, ::String) at loading.jl:1088

**Comment by wildart** [comment]
Your linear constraint is incorrectly defined. It looks like, you wanted `Σ wᵢ = 1` , and you correctly set the constraint lower and upper bounds to 1.0
```
lc = [1.0]
uc = [1.0]
```
But the actual constraint expression is incorrect. If must be a function that have to return value of the type of the bounds, i.e. 1D array, so
```
con_w(w) = [ w[1]+w[2]+w[3]+w[4]+w[5]+w[6] ]
```
