### ISSUE TITLE
error with scramble mutation

### ISSUE THREAD

**Issue by n-salvi** [wildart/Evolutionary.jl#70]
Hello, 

I am trying to optimise an array of booleans:

```
init = ()->Bool[rand(Bool) for el in tc]
opts = Evolutionary.Options(iterations=500)
mthd = GA(populationSize=150, crossoverRate=0.5, mutationRate=0.2, selection=susinv, crossover=uniform(), mutation=scramble())
Random.seed!(10);
result = Evolutionary.optimize(f1, init, mthd, opts)
```

but I keep getting this error:

```
ERROR: LoadError: MethodError: no method matching scramble()
Closest candidates are:
  scramble(!Matched::T) where T<:(AbstractArray{T,1} where T) at /home/nsalvi/.julia/packages/Evolutionary/BIk3j/src/mutations.jl:225
``` 

I am a bit lost, can anyone help me with that?

**Comment by wildart** [comment]
Drop the `()` from in the parameters
```julia
mthd = GA(selection=susinv, crossover=uniform, mutation=scramble)

```
Parenthesis used for the function call, `scramble()` is a function call. However, you need to pass a function, using its name, as a parameter, in order for the function to be called by the algorithm. Look up documentation for the correct usage of the operators. Some of the operators implemented as closures that accept parameters and return functions.

**Comment by n-salvi** [comment]
Thank you for your reply, this fixed it for me. The test files were actually very helpful also.
