### ISSUE TITLE
Errors using PM and MIPM mutations

### ISSUE THREAD

**Issue by mmiller-max** [wildart/Evolutionary.jl#72]
Hi, thanks for the package!

I'm running into a couple of errors with `PM` and `MIPM`

```Julia
using Evolutionary
f(x) = x[1]^2 + 1
x0 = [0]
res = Evolutionary.optimize(f, x0, GA(selection=ranklinear(1), mutation=PM([-1.0], [3.0])))
```
```
ERROR: AssertionError: Need to set p_int for integer variables
```

I think this is because this line needs to pass a dummy value for `p_float` before `p`: https://github.com/wildart/Evolutionary.jl/blob/8555f347e3a18a0a64b9d4d39d9b26c6b8fe8c2d/src/mutations.jl#L189

When I try with `MIPM` I get this
```
julia> res = Evolutionary.optimize(f, x0, GA(selection=ranklinear(1), mutation=MIPM([-1.0], [3.0])))
ERROR: InexactError: Int64(-0.9692105629432188)
```
Which I think is because this line will result in a float always:
https://github.com/wildart/Evolutionary.jl/blob/8555f347e3a18a0a64b9d4d39d9b26c6b8fe8c2d/src/mutations.jl#L209

The second problem goes away when the initial condition is a vector of floats - should it always be this or is the intention for it to work with a vector of ints?

Cheers

**Comment by wildart** [comment]
It's a bug, there is no truncation implemented for for integer values.
