### ISSUE TITLE
Hard constraints implementation

### ISSUE THREAD

**Issue by TheMEGuy** [wildart/Evolutionary.jl#79]
Hi,

is there a way to implement hard constraints using Evolutionary.jl?

Thanks.

**Comment by wildart** [comment]
I am not sure if I understand correctly what is the hard constraint, but if you set lower and upper bound to the same value you'll get an equality constraint.

```julia
julia> ub = [0.0, 1.0]
2-element Vector{Float64}:
 0.0
 1.0

julia> lb = [0.0, 1.0]
2-element Vector{Float64}:
 0.0
 1.0

julia> c = BoxConstraints(lb, ub)
BoxConstraints{Float64}(ConstraintBounds:
  Variables:
    x[1]=0.0, x[2]=1.0
  Linear/nonlinear constraints:)
```

Same you can do with the (non)linear constraints.
