### ISSUE TITLE
Referencing Evolutionary.jl

### ISSUE THREAD

**Issue by tpdsantos** [wildart/Evolutionary.jl#84]
Hi all,

This package helped a lot in my PhD work and now I want to reference it in a scientific paper and in my final PhD dissertation.

How can I reference it?

Thanks in advance and great job ;)

**Comment by wildart** [comment]
Ha, never thought of it, as I maintain it as a side project. I remember to come across some package that had some bibliography information. I'll need to look around to find a proper way to do that. Good luck!

**Comment by wildart** [comment]
https://zenodo.org/record/5110647

**Comment by tpdsantos** [comment]
Just a side note, one of the authors in the citation is "Julia TagBot", is that supposed to be there?

**Comment by wildart** [comment]
Missed it. Damn automation.
