### ISSUE TITLE
Trying to implement Symbolic Regression with multivariate data; not sure how to coerce data appropriately for the fitness function to work.

### ISSUE THREAD

**Issue by johnabs** [wildart/Evolutionary.jl#87]
Hi there,

I'm working on SR with your GP framework; I was able to get it to work with a very simple x~y style data-set, but now I've got something more like (x1,x2,x3)~y. Unfortunately, I'm running into some issues with trying to evaluate the evolutionary expressions on arrays of values when I try to define my fitness function. I'm currently unsure of how to map specific values within the Terminal array to their equivalent data values in the "Evolutionary.Expression(expr).(data)", but I can't even get that far due to a typing constraint on the Evolutionary.Expression.

Below is my very short and naive reparameterization attempt of the initial code (I'm fairly confident the fitobj is the sticking point). If you have a few spare minutes to help me figure this out, I would seriously appreciate it, and I'd be happy to write up some documentation to help clarify this particular use-case for anyone else who may try something similar in the future.

Thank you in advance for any help you're willing/able to provide.

```
file="data2.csv"
data2=CSV.read(file,DataFrame)
terms2 = Terminal[:x1,:x2,:x3]
data=[data2.x1,data2.x2,data2.x3]
fitobj(expr) = sum(abs2.(data2.y - Evolutionary.Expression(expr).(data...)))/length(data2.x1)|> sqrt

Random.seed!(987498737423);
res = Evolutionary.optimize(fitobj,
    TreeGP(50, terms2, funcs,
        mindepth=1,
        maxdepth=5,
        optimizer = GA(
            selection = uniformranking(5),
            ɛ = 0.1,
            mutationRate = 0.85,
            crossoverRate = 0.1,
        ),
    )
)
```

**Comment by johnabs** [comment]
Update: I solved the issue by replacing the broadcast with map, but I had to do some futzing to get it working correctly. 

The updated code, for anyone wondering is as follows:
```

file="data2.csv"
data2=CSV.read(file,DataFrame)
#Add terminals for x1, x2, and x3.
terms2 = Terminal[:x1,:x2,:x3]
funcs = Function[+,-,*,/]
#Create data matrix from data frame
data=hcat(data2.x1,data2.x2,data2.x3)

# 
fitobj(expr) = sum(abs2.(data2.y - map(x->Evolutionary.Expression(expr)(data[x,:]),1:size(data)[1])))

Random.seed!(987498737423);
res = Evolutionary.optimize(fitobj,
    TreeGP(50, terms2, funcs,
        mindepth=1,
        maxdepth=6,
        optimizer = GA(
            selection = uniformranking(5),
            ɛ = 0.1,
            mutationRate = 0.85,
            crossoverRate = 0.1,
        ),
    )
)
```


As a suggestion, would it be possible to have the optimizer automatically discard and re-roll invalid trees (ones with type errors) rather than needing to heavily sanitize the input? I noticed when attempting to use certain operators with constrained domains (e.g. ^), the programs would often error out due to inadvertently creating an imaginary number somewhere (the error message is below).

```
ERROR: DomainError with -0.2:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
```

**Comment by wildart** [comment]
You can use these [protected functions](https://github.com/wildart/Evolutionary.jl/blob/master/src/api/protected.jl) for defining a GP function set to avoid domain errors.
