### ISSUE TITLE
Examples in documentation fail

### ISSUE THREAD

**Issue by albertpod** [wildart/Evolutionary.jl#94]
Hi!

Thank you for the package! 
JFYI, the example from your [docs](https://wildart.github.io/Evolutionary.jl/stable/) fails.
The same applies to [tutorials](https://wildart.github.io/Evolutionary.jl/stable/tutorial/#Optimization).

Regards

**Comment by wildart** [comment]
Thanks for bringing the issue. Please refer to [dev](https://wildart.github.io/Evolutionary.jl/dev/) docs for fixed version.
