### ISSUE TITLE
Cannot get examples MLP to work

### ISSUE THREAD

**Issue by saffdas** [wildart/Evolutionary.jl#96]
Hello-

Thank you for putting this package together. Unfortunately, I've been trying to run GA example, it's giving the following error:
`res = Evolutionary.optimize(fitness, model, algo, opts)`

**Error**

> MethodError: no method matching optimize(::typeof(fitness), ::Chain{Tuple{Dense{typeof(relu), Matrix{Float32}, Vector{Float32}}, Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}}}, ::GA{typeof(rouletteinv), typeof(uniform_mlp), var"#mutation#9"{Evolutionary.var"#mutation#200"{Evolutionary.var"#mutation#199#201"{Float64}}}}, ::Evolutionary.Options{Nothing, TaskLocalRNG}; rng=TaskLocalRNG())
Closest candidates are:
  optimize(::TC, ::Any, ::M, ::Evolutionary.Options) where {TC, M<:Evolutionary.AbstractOptimizer} at C:\Users\DELL\.julia\packages\Evolutionary\65hL6\src\api\optimize.jl:15 got unsupported keyword argument "rng"
  optimize(::TC, ::NLSolversBase.ConstraintBounds, ::M, ::Evolutionary.Options) where {TC, M<:Evolutionary.AbstractOptimizer} at C:\Users\DELL\.julia\packages\Evolutionary\65hL6\src\api\optimize.jl:21 got unsupported keyword argument "rng"
  optimize(::TC, ::TF, ::C, ::Any, ::M) where {TC, TF, M<:Evolutionary.AbstractOptimizer, C<:NLSolversBase.AbstractConstraints} at C:\Users\DELL\.julia\packages\Evolutionary\65hL6\src\api\optimize.jl:44 got unsupported keyword argument "rng"
  ...

>Stacktrace:
 [1] top-level scope
   @ In[71]:2
 [2] eval
   @ .\boot.jl:373 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1196`

I think I should override the following code

`function initial_population(method::M, individual::Chain,kwargs...) where {M<:Evolutionary.AbstractOptimizer}`
`θ, re = Flux.destructure(individual);`
`[re(randn(length(θ))) for i in 1:Evolutionary.population_size(method)]
end`

After a thorough search in code, I'm unable to figure out the way to deal with the extra keyword argument "rng". If anyone could give me some helpful pointers to solve this error message, I'd be grateful. Thanks

**Comment by adigitoleo** [comment]
It will help if you provide a [minimum working example](https://stackoverflow.com/help/minimal-reproducible-example) or show the complete example that fails. I just got a similar error from some old code, but it turns out some of the crossover callables and maybe others have been renamed. Check if you are using up-to-date function names.

**Comment by adigitoleo** [comment]
Based on the error trace, it looks like you are using a function called `uniform_mlp` somewhere, however I don't think it exists anymore. Check the latest documentation for [crossover functions](https://wildart.github.io/Evolutionary.jl/stable/crossover/#Crossover), hopefully you find a new function that is equivalent.

**Comment by wildart** [comment]
I updated the example to work with new version.
